### ISSUE TITLE
Error about starting SC

### ISSUE THREAD

**Issue by ghost** [simonhicks/foxdot.vim#1]
Hi, thanks for making the nice plugin. I want to solve that error...

> Starting SuperCollider...
> Error detected while processing function foxdot#start[1]..<SNR>44_startSuperColl
> ider[9]..foxdot#errHandler:
> line    1:
> executing job failed: No such file or directorydone!
> Starting FoxDot...done!
> LiveCoding with Python and SuperCollider

Maybe is it wrong choosing the absolute path to sclang? Please help me!

Best,
azamiline

**Comment by simonhicks** [comment]
Hey Azamiline,

Yes, it sounds like it's not finding sclang. Have you configured `g:sclang_executable_path` with the correct path to the sclang executable?

**Comment by ghost** [comment]
Yes, I've configured but the path is maybe wrong. How should I get the path to sclang? Now, I use this path: `/Applications/SuperCollider.app/Contents/MacOS/sclang`. Thanks for your reply!

**Comment by ghost** [comment]
`/Library/Application Support/SuperCollider/`etc... are not working well. It seems to I don't understand the construction of FoxDot-SC-Vim X(

**Comment by simonhicks** [comment]
Here are a few things you could test to figure out what's wrong:

- try putting some supercollider code into an `.scd` file, and then run it using the sclang executable
- This script is extremely simple. Maybe you could try putting some debug statements into the `autoload/foxdot.vim` to find out where the vimscript is going wrong.

**Comment by ghost** [comment]
Sorry for delayed reply + FIXED! Thanks a lot!
